---
title: "Data_engineering_chat_analysi"
author: "Yue (Winnie) Wen"
date: "12/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(caret)
library(gam)
library(gridExtra)
library(randomForest)
library(moments)
library(texreg)
library(tidyverse)
library(SentimentAnalysis)
library(SnowballC)
```

```{r}
raw_chat_dat <- read.csv("chat.csv")
```

```{r}
# EXAMPLE !!!
# Create a vector of strings
documents <- c("Wow, I really like the new light sabers!",
               "That book was excellent.",
               "R is a fantastic language.",
               "The service in this restaurant was miserable.",
               "This is neither positive or negative.",
               "The waiter forget about my dessert -- what poor service!")

# Analyze sentiment
sentiment <- analyzeSentiment(documents)

# Extract dictionary-based sentiment according to the QDAP dictionary
sentiment$SentimentQDAP

convertToDirection(sentiment$SentimentQDAP)
```
```{r}
raw_chat_dat$sentiment_score = 0
raw_chat_dat$sentiment = ""

raw_chat_dat$sentiment_score[1:34223] = analyzeSentiment(raw_chat_dat$key[1:34223])$SentimentQDAP
raw_chat_dat$sentiment[1:34223] = convertToDirection(analyzeSentiment(raw_chat_dat$key[1:34223])$SentimentQDAP)

raw_chat_dat$sentiment_score[34223:68446] = analyzeSentiment(raw_chat_dat$key[34223:68446])$SentimentQDAP
raw_chat_dat$sentiment[34223:68446] = convertToDirection(analyzeSentiment(raw_chat_dat$key[34223:68446])$SentimentQDAP)

raw_chat_dat$sentiment_score[68447:102669] = analyzeSentiment(raw_chat_dat$key[68447:102669])$SentimentQDAP
raw_chat_dat$sentiment[68447:102669] = convertToDirection(analyzeSentiment(raw_chat_dat$key[68447:102669])$SentimentQDAP)

raw_chat_dat$sentiment_score[102670:136894] = analyzeSentiment(raw_chat_dat$key[102670:136894])$SentimentQDAP
raw_chat_dat$sentiment[102670:136894] = convertToDirection(analyzeSentiment(raw_chat_dat$key[102670:136894])$SentimentQDAP)
```

```{r}
summary(raw_chat_dat$sentiment_score)
```

```{r}
raw_chat_dat$sentiment_word = ifelse(raw_chat_dat$sentiment == 3, 'positive',
                              ifelse(raw_chat_dat$sentiment == 1, 'negative',
                              ifelse(raw_chat_dat$sentiment == 2, 'neutral', "N/A")))
```


```{r}
class(raw_chat_dat$sentiment_score)
```

```{r}
write.csv(raw_chat_dat, "Chat_with_sentiment.csv")
```

